require("configs.bufferline")
-- require("configs.lualine")
require("configs.nvim-tree")
require("configs.telescope")
require("configs.treesitter")
require("configs.cmp")
require("configs.lsp")
require("configs.dap")
require("configs.colorscheme")
require("configs.autopairs")
require("configs.term")
require("configs.todo")
require("configs.comment")

-- INFO: additions stuff
require("configs.noice")
require("configs.snippets")
-- require("configs.alpha")
require("configs.fold")
require("configs.dev")
