require("minimal.colorscheme")
require("minimal.opts")
require("minimal.keymaps")
require("minimal.plugins")
require("minimal.p-navic")
require("minimal.lsp")

require("minimal.p-nvim-tree")
require("minimal.p-lualine")
require("minimal.p-text")
require("minimal.p-telescope")
require("minimal.p-cmp")
require("minimal.p-null")
require("minimal.p-luasnip")
require("minimal.p-autopairs")
require("minimal.p-treesitter")
require("minimal.p-noice")
require("minimal.p-which-key")
require("minimal.p-ufo")
require("minimal.style")
require("minimal.other")
require("minimal.p-navic")
-- ricing
-- require("vim-startify").setup()
