require("new.configs.lualine")
require("new.configs.nvim-tree")
require("new.configs.telescope")
require("new.configs.treesitter")
require("new.configs.cmp")
require("new.configs.lsp")
require("new.configs.dap")

-- INFO: additions stuff
require("new.configs.colorscheme")
require("new.configs.noice")
require("new.configs.autopairs")
require("new.configs.term")
require("new.configs.snippets")
require("new.configs.alpha")
require("new.configs.fold")
require("new.configs.todo")
require("new.configs.comment")
require("new.configs.bufferline")
require("new.configs.dev")
